# -*- coding: utf-8 -*-
"""Análise de Componentes Principais De Cancer de Mama .ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1t27ypOpE2t_guHLvNNF0G6_u9pX4W2Vb
"""

import pandas as pd
import numpy as np
from sklearn.decomposition import PCA
from sklearn.impute import SimpleImputer
import matplotlib.pyplot as plt

# Carregar o conjunto de dados
data = pd.read_csv('/content/drive/MyDrive/data.csv')

# Visualizar as primeiras linhas do conjunto de dados
print(data.head())

# Separar as features dos rótulos
X = data.iloc[:, 2:].values
y = data.iloc[:, 1].values

# Tratar valores ausentes
imputer = SimpleImputer(strategy='mean')
X = imputer.fit_transform(X)

# Normalizar os dados
X = (X - np.mean(X)) / np.std(X)

# Calcular e imprimir a matriz de covariância
cov_matrix = np.cov(X.T)
print("Matriz de Covariância:")
print(cov_matrix)

# Calcular e imprimir os autovalores e autovetores
eigenvalues, eigenvectors = np.linalg.eig(cov_matrix)
print("\nAutovalores:")
print(eigenvalues)
print("\nAutovetores:")
print(eigenvectors)

# Ordenar os autovalores e autovetores em ordem decrescente
eigen_pairs = [(np.abs(eigenvalues[i]), eigenvectors[:, i]) for i in range(len(eigenvalues))]
eigen_pairs.sort(key=lambda x: x[0], reverse=True)

# Selecionar os dois maiores autovalores e autovetores
top_eigenvalues = eigen_pairs[0][0], eigen_pairs[1][0]
top_eigenvectors = eigen_pairs[0][1], eigen_pairs[1][1]

print("\nDois maiores autovalores:")
print(top_eigenvalues)
print("\nDois maiores autovetores:")
print(top_eigenvectors)

# Aplicar PCA com 3 componentes principais
pca = PCA(n_components=3)
X_pca = pca.fit_transform(X)

# Converter rótulos para valores numéricos
label_map = {'M': 0, 'B': 1}
y_numeric = np.array([label_map[label] for label in y])

# Visualizar os resultados
plt.scatter(X_pca[:, 0], X_pca[:, 1], c=y_numeric, cmap='viridis')
plt.xlabel('Componente Principal 1')
plt.ylabel('Componente Principal 2')
plt.title('Análise de PCA - Câncer de Mama')
plt.show()

